# Generated by Django 3.2.7 on 2021-11-04 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'category_table',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('movie_name', models.CharField(max_length=30)),
                ('hero', models.CharField(blank=True, max_length=30)),
                ('heroine', models.CharField(blank=True, max_length=30)),
                ('Director', models.CharField(max_length=30)),
                ('Genre_name', models.CharField(default=None, max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'history_table',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobileno', models.BigIntegerField(unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=30)),
                ('hero', models.CharField(blank=True, max_length=30)),
                ('heroine', models.CharField(blank=True, max_length=30)),
                ('Director', models.CharField(max_length=30)),
                ('Release_year', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Duration', models.CharField(max_length=10)),
                ('Genre_name', models.CharField(default=None, max_length=30)),
                ('Description', models.CharField(max_length=500)),
                ('Genre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Movies.category')),
            ],
            options={
                'db_table': 'movie_table',
            },
        ),
    ]
